language: csharp
solution: Imgix-CSharp.sln

install:
  - msbuild /t:Restore Imgix-CSharp.sln
script:
  - msbuild /p:Configuration=Release Imgix-CSharp.sln
  - dotnet test ./CryptographyTests/bin/Release/net46/CryptographyTests.dll
  - dotnet test ./Imgix-CSharp-Tests/bin/Release/net46/ImgixClientTests.dll