language: csharp
dist: trusty
mono: none
dotnet: 2.0.0

install:
  - dotnet restore
script:
  - dotnet build
  - dotnet test ./CryptographyTests/bin/Release/net46/CryptographyTests.dll
  - dotnet test ./Imgix-CSharp-Tests/bin/Release/net46/ImgixClientTests.dll