version: 2.1
orbs:
  win: circleci/windows@5.0.0
  
jobs:
  test:
    executor: win/default
    steps:
      - checkout
      - run:
          name: Install
          command: | 
            msbuild /t:Restore imgix-csharp.sln
            nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
            msbuild /p:Configuration=Release imgix-csharp.sln
      - run:
          name: Tests
          command: dotnet test

workflows:
  test:
    jobs:
      - test